# Generated by Django 5.0.7 on 2024-07-12 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 3, 59, 951612)),
        ),
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 3, 59, 952034)),
        ),
        migrations.AddField(
            model_name='questionexamples',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 3, 59, 952455)),
        ),
    ]
