# Generated by Django 5.0.7 on 2024-07-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_category_created_date_question_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='questionexamples',
            name='created_date',
        ),
    ]
