# Generated by Django 5.0.7 on 2024-07-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_category_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionExamples',
        ),
    ]
