# Generated by Django 5.0.7 on 2024-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_delete_questionexamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='a+b', max_length=255),
        ),
    ]
