# Generated by Django 5.0.7 on 2024-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
