# Generated by Django 5.0.7 on 2024-07-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_date',
        ),
    ]
